manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: eyalye
      url-base: https://github.com/eyalye
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display
      remote: eyalye
      revision: main
    - name: zmk-paw3395-driver
      remote: badjeff
      revision: main
  self:
    path: config
